###  Numpy

Numpy is a Fundamentals library for scientific computing in Python. It provides support for arrays and matrics, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [4]:
!pip install numpy

In [5]:
import numpy as np

## create arrays using numpy
## create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ##1 row and 5 columns


array([[1, 2, 3, 4, 5]])

In [9]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [10]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
